= 静态库
:toc:
:toc-placement!:

toc::[]

# 介绍

本节示例功能：

创建并链接静态库，并通过生成一个可执行文件查看结果。并且该项目也会在 link:../../02-sub-projects[02-sub-projects] 中体现。

文件结构如下:

```
$ tree
.
├── CMakeLists.txt
├── include
│   └── static
│       └── Hello.h
└── src
    ├── Hello.cpp
    └── main.cpp
```

  * link:CMakeLists.txt[] - 包含可执行的Cmake命令
  * link:include/static/Hello.h[] - 包含的头文件
  * link:src/Hello.cpp[] - 待编译的源文件
  * link:src/main.cpp[] - 可执行的源文件


# 思路

## 添加静态库

+add_library()+ 函数用于从某些源文件创建库。命令为

[source,cmake]
----
add_library(hello_library STATIC 
    src/Hello.cpp
)
----

这将用于创建一个名为 libhello_library.a 或 libhello_library.lib 的静态库，其中包含 +add_library+ 调用中的源。

[NOTE]
====
如所示代码，现代 CMake 采用源文件直接传递给 +add_library+ 调用的方式。
====

## 包含头文件

例子中，采用 +target_include_directories()+ 函数传递头文件所在目录，且将其作用域设为 +PUBLIC+。

[source,cmake]
----
target_include_directories(hello_library
    PUBLIC 
        ${PROJECT_SOURCE_DIR}/include
)
----

设置为 +PUBLIC+ 将导致在以下位置会使用头文件目录：

* 编译库时
* 编译链接库的任何其他目标时

作用域的含义:

* +PRIVATE+ - 该目录仅添加到目标的头文件目录
* +INTERFACE+ - 该目录将添加到链接此库的任何目标的头文件目录中
* +PUBLIC+ - 如上所述，它包含在此库中，也包含在链接此库的任何目标中


[TIP]
====
对于公共头文件，通常最好将包含文件夹与子目录一起"命名空间化"。

传递给 +target_include_directories+ 目录将是头文件的根目录，C++文件应能从该根目录找到所需要的头文件。


对于此示例，您可以看到我们按如下方式执行此操作：

例子中，传入的头文件目录为应为static文件夹所在的目录，而引用时，应指定具体的路径

[source,cpp]
----
#include "static/Hello.h"
----

这样做的好处是，在项目中使用多个库时，标头文件名冲突的可能性较小。
====

## 链接库

当创建可执行文件时，你必须告诉编译器你使用的库。通过 +target_link_libraries()+ 可以轻松解决。

[source,cmake]
----
add_executable(hello_binary 
    src/main.cpp
)

target_link_libraries( hello_binary
    PRIVATE  
        hello_library
)
----

这告诉 CMake 在链接过程中将 hello_library 与 hello_binary 链接起来。这还将从链接库目标传播具有 +PUBLIC+ 或 +INTERFACE+ 作用域的任何头文件目录。

Linux 下连接器的命令

```
/usr/bin/c++ CMakeFiles/hello_binary.dir/src/main.cpp.o -o hello_binary -rdynamic libhello_library.a
```


# 构建示例
可直接运行 build.bat 一键完成以下操作。

## Linux

[source,bash]
----
$ mkdir build

$ cd build

$ cmake ..
-- The C compiler identification is GNU 4.8.4
-- The CXX compiler identification is GNU 4.8.4
-- Check for working C compiler: /usr/bin/cc
-- Check for working C compiler: /usr/bin/cc -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Check for working CXX compiler: /usr/bin/c++
-- Check for working CXX compiler: /usr/bin/c++ -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Configuring done
-- Generating done
-- Build files have been written to: /home/matrim/workspace/cmake-examples/01-basic/C-static-library/build

$ make
Scanning dependencies of target hello_library
[ 50%] Building CXX object CMakeFiles/hello_library.dir/src/Hello.cpp.o
Linking CXX static library libhello_library.a
[ 50%] Built target hello_library
Scanning dependencies of target hello_binary
[100%] Building CXX object CMakeFiles/hello_binary.dir/src/main.cpp.o
Linking CXX executable hello_binary
[100%] Built target hello_binary

$ ls
CMakeCache.txt  CMakeFiles  cmake_install.cmake  hello_binary  libhello_library.a  Makefile

$ ./hello_binary
Hello Static Library!
----

## Windows

[source,bash]
----
$ mkdir build

$ cd build

$ cmake ..
-- Building for: Visual Studio 16 2019
-- Selecting Windows SDK version  to target Windows 10.0.19042.
-- The C compiler identification is MSVC 19.29.30133.0
-- The CXX compiler identification is MSVC 19.29.30133.0
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Check for working C compiler: C:/Program Files (x86)/Microsoft Visual Studio/2019/Community/VC/Tools/MSVC/14.29.30133/bin/Hostx64/x64/cl.exe - skipped
-- Detecting C compile features
-- Detecting C compile features - done
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Check for working CXX compiler: C:/Program Files (x86)/Microsoft Visual Studio/2019/Community/VC/Tools/MSVC/14.29.30133/bin/Hostx64/x64/cl.exe - skipped
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- Configuring done
-- Generating done
-- Build files have been written to: D:/Project/CPP/cmake-examples/01-basic/C-static-library/build

$ cmake --build .
Checking Build System
Building Custom Rule D:/Project/CPP/cmake-examples/01-basic/C-static-library/CMakeLists.txt
Hello.cpp
hello_library.vcxproj -> D:\Project\CPP\cmake-examples\01-basic\C-static-library\build\Debug\hello_library.lib
Building Custom Rule D:/Project/CPP/cmake-examples/01-basic/C-static-library/CMakeLists.txt
main.cpp
hello_binary.vcxproj -> D:\Project\CPP\cmake-examples\01-basic\C-static-library\build\Debug\hello_binary.exe
Building Custom Rule D:/Project/CPP/cmake-examples/01-basic/C-static-library/CMakeLists.txt

$ ls .\Debug\
Mode                 LastWriteTime         Length Name                                                                                                                                                                                               
----                 -------------         ------ ----                                                                                                                                                                                               
-a----        2021/11/30     20:18          58880 hello_binary.exe
-a----        2021/11/30     20:18        1036288 hello_binary.pdb
-a----        2021/11/30     20:18          53974 hello_library.lib
-a----        2021/11/30     20:18         405504 hello_library.pdb                                                                                                                                                                                  


$ .\Debug\hello_cmake.exe
Hello Static Library!
----

